### PR TITLE
add huobi wallet

### PR DESCRIPTION
**Pull request by enoughpower**
add huobi wallet

### CODE REVIEW

**Comment by obiedobo** [comment]
Hey @enoughpower, thanks for submitting! It looks like there are some conflicts and the checks aren't passing, could you troubleshoot and commit a fix? Make sure to build and test locally if you didn't already!

**Comment by yuquan08211** [comment]
Merge branch 'main' into huobi-wallet, please review~,thanks

**Comment by obiedobo** [comment]
The build is still failing, can you ensure this is working before we merge? Thanks!

**Comment by obiedobo** [comment]
Hey there! Just an update here :)

If you'd like to have Huobi added to our UI, would you be able to create a PR into `main-v-2`?

We are actually in the process of deprecating the `main` branch, and are no longer accepting PRs into `main` :)

**Pull request closed without merging**
