### PR TITLE
Coinbase wallet james

### PR DESCRIPTION
**Pull request by jamesbane**
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/apeswap/apeswap-uikit/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

### CODE REVIEW

**Comment by obiedobo** [comment]
Thanks for the PR @jamesbane! But I see 4700 lines have been updated on the lock.json file. Not sure what's going on there, but can you look into it?

**Comment by apewukong** [comment]
@jamesbane Thanks for the PR, regarding the `yarn.lock` update, can you let us know what node version you work on with? Also do you mind sharing the OS, whether Windows/Linux/Mac?

**Comment by jamesbane** [comment]
we can ignore it, yarn.lock is changing every time when yarn install
Hi @apewukong 
I am using node16.13.0 and system is macos

**Comment by apewukong** [comment]
> 

Oh I see, we normally recommend use node `v14.x.x` (mine is 14.17.0) for our frontend repo. That might be a reason for yanr.lock file update

**Comment by jamesbane** [comment]
ok I will downgrade node version to 14x

**Pull request merged**
